
// Music genres
#define MusicGenreCount 203
LFMusicGenre MusicGenres[MusicGenreCount] = {
	{ L"", IDI_FLD_NOTE },
	{ L"Abstract", IDI_FLD_ELECTRONIC },
	{ L"Acapella", IDI_FLD_NOTE },
	{ L"Acid Jazz", IDI_FLD_JAZZ },
	{ L"Acid Punk", IDI_FLD_NOTE },
	{ L"Acid", IDI_FLD_NOTE },
	{ L"Acoustic", IDI_FLD_NOTE },
	{ L"Alternative Rock", IDI_FLD_ALTERNATIVE },
	{ L"Alternative", IDI_FLD_ALTERNATIVE },
	{ L"AlternRock", IDI_FLD_ALTERNATIVE },
	{ L"Ambient", IDI_FLD_AMBIENT },
	{ L"Anime", IDI_FLD_SOUNDTRACKS },
	{ L"Art Rock", IDI_FLD_ROCK },
	{ L"Audio Theatre", IDI_FLD_REDCURTAIN },
	{ L"Audiobook", IDI_FLD_NOTE },
	{ L"Avantgarde", IDI_FLD_NOTE },
	{ L"Ballad", IDI_FLD_NOTE },
	{ L"Baroque", IDI_FLD_CLASSICAL },
	{ L"Bass", IDI_FLD_NOTE },
	{ L"Beat", IDI_FLD_OLDIES },
	{ L"Bebob", IDI_FLD_NOTE },
	{ L"Bhangra", IDI_FLD_NOTE },
	{ L"Big Band", IDI_FLD_NOTE },
	{ L"Big Beat", IDI_FLD_NOTE },
	{ L"Black Metal", IDI_FLD_METAL },
	{ L"Bluegrass", IDI_FLD_NOTE },
	{ L"Blues", IDI_FLD_BLUES },
	{ L"Bollywood", IDI_FLD_NOTE },
	{ L"Booty Bass", IDI_FLD_NOTE },
	{ L"Breakbeat", IDI_FLD_ELECTRONIC },
	{ L"Britpop", IDI_FLD_POP },
	{ L"Cabaret", IDI_FLD_REDCURTAIN },
	{ L"Celtic", IDI_FLD_NOTE },
	{ L"Chamber Music", IDI_FLD_CLASSICAL },
	{ L"Chanson", IDI_FLD_REDCURTAIN },
	{ L"Chillout", IDI_FLD_ELECTRONIC },
	{ L"Chorus", IDI_FLD_REDCURTAIN },
	{ L"Christian Gangsta Rap", IDI_FLD_NOTE },
	{ L"Christian Rap", IDI_FLD_NOTE },
	{ L"Christian Rock", IDI_FLD_NOTE },
	{ L"Classic Rock", IDI_FLD_ROCK },
	{ L"Classical", IDI_FLD_CLASSICAL },
	{ L"Club", IDI_FLD_DANCE },
	{ L"Club-House", IDI_FLD_ELECTRONIC },
	{ L"Comedy", IDI_FLD_REDCURTAIN },
	{ L"Contemporary Christian", IDI_FLD_NOTE },
	{ L"Country", IDI_FLD_COUNTRY },
	{ L"Crossover", IDI_FLD_ALTERNATIVE },
	{ L"Cult", IDI_FLD_NOTE },
	{ L"Dance & DJ", IDI_FLD_DANCE },
	{ L"Dance Hall", IDI_FLD_REGGAE },
	{ L"Dance", IDI_FLD_DANCE },
	{ L"Darkwave", IDI_FLD_NOTE },
	{ L"Death Metal", IDI_FLD_METAL },
	{ L"Disco", IDI_FLD_DANCE },
	{ L"Downtempo", IDI_FLD_NOTE },
	{ L"Dream", IDI_FLD_AMBIENT },
	{ L"Drum & Bass", IDI_FLD_ELECTRONIC },
	{ L"Drum Solo", IDI_FLD_NOTE },
	{ L"Dub", IDI_FLD_REGGAE },
	{ L"Dubstep", IDI_FLD_REGGAE },
	{ L"Duet", IDI_FLD_NOTE },
	{ L"Easy Listening", IDI_FLD_EASYLISTENING },
	{ L"EBM", IDI_FLD_ELECTRONIC },
	{ L"Eclectic", IDI_FLD_NOTE },
	{ L"Electro", IDI_FLD_ELECTRONIC },
	{ L"Electroclash", IDI_FLD_ELECTRONIC },
	{ L"Electronic", IDI_FLD_ELECTRONIC },
	{ L"Emo", IDI_FLD_ALTERNATIVE },
	{ L"Ethnic", IDI_FLD_WORLDMUSIC },
	{ L"Euro-House", IDI_FLD_ELECTRONIC },
	{ L"Euro-Techno", IDI_FLD_ELECTRONIC },
	{ L"Eurodance", IDI_FLD_DANCE },
	{ L"Europop", IDI_FLD_POP },
	{ L"Experimental", IDI_FLD_NOTE },
	{ L"Fast Fusion", IDI_FLD_NOTE },
	{ L"Folk", IDI_FLD_NOTE },
	{ L"Folk-Rock", IDI_FLD_NOTE },
	{ L"Folklore", IDI_FLD_NOTE },
	{ L"Freestyle", IDI_FLD_NOTE },
	{ L"Funk", IDI_FLD_NOTE },
	{ L"Fusion", IDI_FLD_NOTE },
	{ L"G-Funk", IDI_FLD_NOTE },
	{ L"Game", IDI_FLD_NOTE },
	{ L"Gangsta", IDI_FLD_HIPHOP },
	{ L"Gangsta Rap", IDI_FLD_HIPHOP },
	{ L"Garage Rock", IDI_FLD_ROCK },
	{ L"Garage", IDI_FLD_ELECTRONIC },
	{ L"Global", IDI_FLD_NOTE },
	{ L"Goa", IDI_FLD_NOTE },
	{ L"Gospel", IDI_FLD_NOTE },
	{ L"Gothic Rock", IDI_FLD_ROCK },
	{ L"Gothic", IDI_FLD_NOTE },
	{ L"Grunge", IDI_FLD_ALTERNATIVE },
	{ L"Hard Rock", IDI_FLD_ROCK },
	{ L"Hardcore", IDI_FLD_NOTE },
	{ L"Heavy Metal", IDI_FLD_METAL },
	{ L"Hip-Hop", IDI_FLD_HIPHOP },
	{ L"House", IDI_FLD_ELECTRONIC },
	{ L"Humour", IDI_FLD_REDCURTAIN },
	{ L"IDM", IDI_FLD_NOTE },
	{ L"Illbient", IDI_FLD_ELECTRONIC },
	{ L"Indie Rock", IDI_FLD_ALTERNATIVE },
	{ L"Indie", IDI_FLD_ALTERNATIVE },
	{ L"Industrial", IDI_FLD_NOTE },
	{ L"Industro-Goth", IDI_FLD_NOTE },
	{ L"Instrumental Pop", IDI_FLD_POP },
	{ L"Instrumental Rock", IDI_FLD_ROCK },
	{ L"Instrumental", IDI_FLD_NOTE },
	{ L"International", IDI_FLD_WORLDMUSIC },
	{ L"Jam Band", IDI_FLD_NOTE },
	{ L"Jazz", IDI_FLD_JAZZ },
	{ L"Jazz+Funk", IDI_FLD_JAZZ },
	{ L"J-Pop", IDI_FLD_JPOP },
	{ L"Jungle", IDI_FLD_ELECTRONIC },
	{ L"Krautrock", IDI_FLD_ROCK },
	{ L"Latin", IDI_FLD_LATIN },
	{ L"Leftfield", IDI_FLD_NOTE },
	{ L"Lo-Fi", IDI_FLD_NOTE },
	{ L"Lounge", IDI_FLD_AMBIENT },
	{ L"Math Rock", IDI_FLD_NOTE },
	{ L"Meditative", IDI_FLD_AMBIENT },
	{ L"Merengue", IDI_FLD_LATIN },
	{ L"Metal", IDI_FLD_METAL },
	{ L"Musical", IDI_FLD_REDCURTAIN },
	{ L"National Folk", IDI_FLD_NOTE },
	{ L"Native US", IDI_FLD_WORLDMUSIC },
	{ L"Negerpunk", IDI_FLD_NOTE },
	{ L"Neoclassical", IDI_FLD_CLASSICAL },
	{ L"Neue Deutsche Welle", IDI_FLD_POP },
	{ L"New Age", IDI_FLD_AMBIENT },
	{ L"New Romantic", IDI_FLD_AMBIENT },
	{ L"New Wave", IDI_FLD_NOTE },
	{ L"Noise", IDI_FLD_NOTE },
	{ L"Nu-Breakz", IDI_FLD_ELECTRONIC },
	{ L"Oldie", IDI_FLD_OLDIES },
	{ L"Oldies", IDI_FLD_OLDIES },
	{ L"Opera", IDI_FLD_CLASSICAL },
	{ L"Other", IDI_FLD_NOTE },
	{ L"Podcast", IDI_FLD_SPOKENWORD },
	{ L"Polka", IDI_FLD_NOTE },
	{ L"Polsk Punk", IDI_FLD_NOTE },
	{ L"Pop", IDI_FLD_POP },
	{ L"Pop-Folk", IDI_FLD_POP },
	{ L"Pop-Punk", IDI_FLD_POP },
	{ L"Porn Groove", IDI_FLD_NOTE },
	{ L"Post-Punk", IDI_FLD_NOTE },
	{ L"Post-Rock", IDI_FLD_NOTE },
	{ L"Power Ballad", IDI_FLD_NOTE },
	{ L"Pranks", IDI_FLD_NOTE },
	{ L"Primus", IDI_FLD_NOTE },
	{ L"Progressive Rock", IDI_FLD_ROCK },
	{ L"PsybientSynthPop", IDI_FLD_POP },
	{ L"Psychadelic", IDI_FLD_NOTE },
	{ L"Psychedelic Rock", IDI_FLD_ROCK },
	{ L"Psytrance", IDI_FLD_ELECTRONIC },
	{ L"Punk Rock", IDI_FLD_NOTE },
	{ L"Punk", IDI_FLD_NOTE },
	{ L"R&B", IDI_FLD_RANDB },
	{ L"Rap & Hip-Hop", IDI_FLD_HIPHOP },
	{ L"Rap", IDI_FLD_HIPHOP },
	{ L"Rave", IDI_FLD_ELECTRONIC },
	{ L"Reggae", IDI_FLD_REGGAE },
	{ L"Retro", IDI_FLD_OLDIES },
	{ L"Revival", IDI_FLD_NOTE },
	{ L"Rhythmic Soul", IDI_FLD_SOUL },
	{ L"Rock & Roll", IDI_FLD_ROCK },
	{ L"Rock", IDI_FLD_ROCK },
	{ L"Salsa", IDI_FLD_LATIN },
	{ L"Samba", IDI_FLD_LATIN },
	{ L"Satire", IDI_FLD_SPOKENWORD },
	{ L"Shoegaze", IDI_FLD_ROCK },
	{ L"Showtunes", IDI_FLD_NOTE },
	{ L"Ska", IDI_FLD_NOTE },
	{ L"Slow Jam", IDI_FLD_NOTE },
	{ L"Slow Rock", IDI_FLD_ROCK },
	{ L"Sonata", IDI_FLD_NOTE },
	{ L"Soul", IDI_FLD_SOUL },
	{ L"Sound Clip", IDI_FLD_NOTE },
	{ L"Soundtrack", IDI_FLD_SOUNDTRACKS },
	{ L"Soundtracks", IDI_FLD_SOUNDTRACKS },
	{ L"Southern Rock", IDI_FLD_ROCK },
	{ L"Space Rock", IDI_FLD_ROCK },
	{ L"Space", IDI_FLD_AMBIENT },
	{ L"Speech", IDI_FLD_SPOKENWORD },
	{ L"Swing", IDI_FLD_NOTE },
	{ L"Symphonic Rock", IDI_FLD_CLASSICAL },
	{ L"Symphony", IDI_FLD_CLASSICAL },
	{ L"Tango", IDI_FLD_LATIN },
	{ L"Techno", IDI_FLD_ELECTRONIC },
	{ L"Techno-Industrial", IDI_FLD_ELECTRONIC },
	{ L"Terror", IDI_FLD_ELECTRONIC },
	{ L"Thrash Metal", IDI_FLD_METAL },
	{ L"Top 100", IDI_FLD_NOTE },
	{ L"Top 40", IDI_FLD_NOTE },
	{ L"Trailer", IDI_FLD_SOUNDTRACKS },
	{ L"Trance", IDI_FLD_ELECTRONIC },
	{ L"Tribal", IDI_FLD_NOTE },
	{ L"Trip-Hop", IDI_FLD_ELECTRONIC },
	{ L"Trop Rock", IDI_FLD_ROCK },
	{ L"Variété Française", IDI_FLD_NOTE },
	{ L"Vocal", IDI_FLD_REDCURTAIN },
	{ L"World Music", IDI_FLD_WORLDMUSIC }
};
