
// Music genres
#define MusicGenreCount 204
LFMusicGenre MusicGenres[MusicGenreCount] = {
	{ L"Abstract", 0 },
	{ L"Acapella", 0 },
	{ L"Acid Jazz", 0 },
	{ L"Acid Punk", 0 },
	{ L"Acid", 0 },
	{ L"Acoustic", 0 },
	{ L"Alternative Rock", 0 },
	{ L"Alternative", 0 },
	{ L"AlternRock", 0 },
	{ L"Ambient", 0 },
	{ L"Anime", 0 },
	{ L"Art Rock", 0 },
	{ L"Audio Theatre", 0 },
	{ L"Audiobook", 0 },
	{ L"Avantgarde", 0 },
	{ L"Ballad", 0 },
	{ L"Baroque", 0 },
	{ L"Bass", 0 },
	{ L"Beat", 0 },
	{ L"Bebob", 0 },
	{ L"Bhangra", 0 },
	{ L"Big Band", 0 },
	{ L"Big Beat", 0 },
	{ L"Black Metal", 0 },
	{ L"Bluegrass", 0 },
	{ L"Blues", 0 },
	{ L"Bollywood", 0 },
	{ L"Booty Bass", 0 },
	{ L"Breakbeat", 0 },
	{ L"BritPop", 0 },
	{ L"Cabaret", 0 },
	{ L"Celtic", 0 },
	{ L"Chamber Music", 0 },
	{ L"Chanson", 0 },
	{ L"Chillout", 0 },
	{ L"Chorus", 0 },
	{ L"Christian Gangsta Rap", 0 },
	{ L"Christian Rap", 0 },
	{ L"Christian Rock", 0 },
	{ L"Classic Rock", 0 },
	{ L"Classical", 0 },
	{ L"Club", 0 },
	{ L"Club-House", 0 },
	{ L"Comedy", 0 },
	{ L"Contemporary Christian", 0 },
	{ L"Country", 0 },
	{ L"Crossover", 0 },
	{ L"Cult", 0 },
	{ L"Dance & DJ", 0 },
	{ L"Dance Hall", 0 },
	{ L"Dance", 0 },
	{ L"Darkwave", 0 },
	{ L"Death Metal", 0 },
	{ L"Disco", 0 },
	{ L"Downtempo", 0 },
	{ L"Dream", 0 },
	{ L"Drum & Bass", 0 },
	{ L"Drum Solo", 0 },
	{ L"Dub", 0 },
	{ L"Dubstep", 0 },
	{ L"Duet", 0 },
	{ L"Easy Listening", 0 },
	{ L"EBM", 0 },
	{ L"Eclectic", 0 },
	{ L"Electro", 0 },
	{ L"Electroclash", 0 },
	{ L"Electronic", 0 },
	{ L"Emo", 0 },
	{ L"Ethnic", 0 },
	{ L"Euro-House", 0 },
	{ L"Euro-Techno", 0 },
	{ L"Eurodance", 0 },
	{ L"Europop", 0 },
	{ L"Experimental", 0 },
	{ L"Fast Fusion", 0 },
	{ L"Folk", 0 },
	{ L"Folk-Rock", 0 },
	{ L"Folklore", 0 },
	{ L"Freestyle", 0 },
	{ L"Funk", 0 },
	{ L"Funk", 0 },
	{ L"Fusion", 0 },
	{ L"G-Funk", 0 },
	{ L"Game", 0 },
	{ L"Gangsta", 0 },
	{ L"Garage Rock", 0 },
	{ L"Garage", 0 },
	{ L"Global", 0 },
	{ L"Goa", 0 },
	{ L"Gospel", 0 },
	{ L"Gothic Rock", 0 },
	{ L"Gothic", 0 },
	{ L"Grunge", 0 },
	{ L"Hard Rock", 0 },
	{ L"Hardcore", 0 },
	{ L"Heavy Metal", 0 },
	{ L"Hip-Hop", 0 },
	{ L"House", 0 },
	{ L"Humour", 0 },
	{ L"IDM", 0 },
	{ L"Illbient", 0 },
	{ L"Indie Rock", 0 },
	{ L"Indie", 0 },
	{ L"Industrial", 0 },
	{ L"Industro-Goth", 0 },
	{ L"Instrumental Pop", 0 },
	{ L"Instrumental Rock", 0 },
	{ L"Instrumental", 0 },
	{ L"International", 0 },
	{ L"Jam Band", 0 },
	{ L"Jazz", 0 },
	{ L"Jazz+Funk", 0 },
	{ L"JPop", 0 },
	{ L"Jungle", 0 },
	{ L"Krautrock", 0 },
	{ L"Latin", 0 },
	{ L"Leftfield", 0 },
	{ L"Lo-Fi", 0 },
	{ L"Lounge", 0 },
	{ L"Math Rock", 0 },
	{ L"Meditative", 0 },
	{ L"Merengue", 0 },
	{ L"Metal", 0 },
	{ L"Musical", 0 },
	{ L"National Folk", 0 },
	{ L"Native US", 0 },
	{ L"Negerpunk", 0 },
	{ L"Neoclassical", 0 },
	{ L"Neue Deutsche Welle", 0 },
	{ L"New Age", 0 },
	{ L"New Romantic", 0 },
	{ L"New Wave", 0 },
	{ L"Noise", 0 },
	{ L"Nu-Breakz", 0 },
	{ L"Oldie", 0 },
	{ L"Oldies", 0 },
	{ L"Opera", 0 },
	{ L"Other", 0 },
	{ L"Podcast", 0 },
	{ L"Polka", 0 },
	{ L"Polsk Punk", 0 },
	{ L"Pop", 0 },
	{ L"Pop-Folk", 0 },
	{ L"Pop-Punk", 0 },
	{ L"Porn Groove", 0 },
	{ L"Post-Punk", 0 },
	{ L"Post-Rock", 0 },
	{ L"Power Ballad", 0 },
	{ L"Pranks", 0 },
	{ L"Primus", 0 },
	{ L"Progressive Rock", 0 },
	{ L"PsybientSynthPop", 0 },
	{ L"Psychadelic", 0 },
	{ L"Psychedelic Rock", 0 },
	{ L"Psytrance", 0 },
	{ L"Punk Rock", 0 },
	{ L"Punk", 0 },
	{ L"R&B", 0 },
	{ L"Rap & Hip-Hop", 0 },
	{ L"Rap", 0 },
	{ L"Rave", 0 },
	{ L"Reggae", 0 },
	{ L"Retro", 0 },
	{ L"Revival", 0 },
	{ L"Rhytmic Soul", 0 },
	{ L"Rock & Roll", 0 },
	{ L"Rock", 0 },
	{ L"Salsa", 0 },
	{ L"Samba", 0 },
	{ L"Satire", 0 },
	{ L"Shoegaze", 0 },
	{ L"Showtunes", 0 },
	{ L"Ska", 0 },
	{ L"Slow Jam", 0 },
	{ L"Slow Rock", 0 },
	{ L"Sonata", 0 },
	{ L"Soul", 0 },
	{ L"Sound Clip", 0 },
	{ L"Soundtrack", 0 },
	{ L"Soundtracks", 0 },
	{ L"Southern Rock", 0 },
	{ L"Space Rock", 0 },
	{ L"Space", 0 },
	{ L"Speech", 0 },
	{ L"Swing", 0 },
	{ L"Symphonic Rock", 0 },
	{ L"Symphony", 0 },
	{ L"Tango", 0 },
	{ L"Techno", 0 },
	{ L"Techno-Industrial", 0 },
	{ L"Terror", 0 },
	{ L"Thrash Metal", 0 },
	{ L"Top 100", 0 },
	{ L"Top 40", 0 },
	{ L"Trailer", 0 },
	{ L"Trance", 0 },
	{ L"Tribal", 0 },
	{ L"Trip-Hop", 0 },
	{ L"Trop Rock", 0 },
	{ L"Variété Française", 0 },
	{ L"Vocal", 0 },
	{ L"World Music", 0 }
};
