//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LFCore.rc
//
#define IDI_FLD_Default                 1
#define IDI_FLD_All                     2
#define IDI_FLD_Archive                 3
#define IDI_FLD_Audio                   4
#define IDI_FLD_Calendar                5
#define IDI_FLD_Contacts                6
#define IDI_FLD_Documents               7
#define IDI_FLD_Favorites               8
#define IDI_FLD_Fonts                   9
#define IDI_FLD_Location                10
#define IDI_FLD_Mail                    11
#define IDI_FLD_Photos                  12
#define IDI_FLD_Pictures                13
#define IDI_FLD_Presentations           14
#define IDI_FLD_Roll                    15
#define IDI_FLD_Spreadsheets            16
#define IDI_FLD_System                  17
#define IDI_FLD_Trash                   18
#define IDI_FLD_Video                   19
#define IDI_FLD_Web                     20
#define IDI_STORE_Internal              21
#define IDI_STORE_Default               22
#define IDI_STORE_Bag                   23
#define IDI_STORE_Server                24
#define IDI_LastIcon                    24
#define IDS_FirstItemCategory           1000
#define IDS_LFCategoryInternalStores    1000
#define IDS_LFCategoryHybridStores      1001
#define IDS_LFCategoryExternalStores    1002
#define IDS_LFCategoryRemoteStores      1003
#define IDS_LFCategoryDrives            1004
#define IDS_LFCategoryStore             1005
#define IDS_LFCategoryMediaTypes        1006
#define IDS_LFCategoryDocuments         1007
#define IDS_LFCategoryHousekeeping      1008
#define IDS_LFCategoryNight             1009
#define IDS_FirstAttrCategory           1050
#define IDS_LFCategoryBasic             1050
#define IDS_LFCategoryGeotagging        1051
#define IDS_LFCategoryVisual            1052
#define IDS_LFCategoryPhotographic      1053
#define IDS_LFCategoryAudio             1054
#define IDS_LFCategoryTimebased         1055
#define IDS_LFCategoryBibliographic     1056
#define IDS_LFCategoryWorkflow          1057
#define IDS_LFCategoryInternal          1058
#define IDS_BacklinkName                1100
#define IDS_BacklinkDescription         1101
#define IDS_StoreDefaultName            1102
#define IDS_LastSeen                    1103
#define IDS_SeenOn                      1104
#define IDS_ErrorCaption                1105
#define IDS_DeleteStoreCaption          1106
#define IDS_DeleteStoreMessage          1107
#define IDS_ShortcutCaption             1108
#define IDS_ShortcutMessage             1109
#define IDS_HintSingular                1110
#define IDS_HintPlural                  1111
#define IDS_Rating1                     1112
#define IDS_Rating2                     1113
#define IDS_Rating3                     1114
#define IDS_Rating4                     1115
#define IDS_Rating5                     1116
#define IDS_Priority1                   1117
#define IDS_Priority2                   1118
#define IDS_Priority3                   1119
#define IDS_Priority4                   1120
#define IDS_Priority5                   1121
#define IDS_Size1                       1122
#define IDS_Size2                       1123
#define IDS_Size3                       1124
#define IDS_Size4                       1125
#define IDS_Size5                       1126
#define IDS_Size6                       1127
#define IDS_Duration1                   1128
#define IDS_Duration2                   1129
#define IDS_Duration3                   1130
#define IDS_Duration4                   1131
#define IDS_Duration5                   1132
#define IDS_Duration6                   1133
#define IDS_Duration7                   1134
#define IDS_Duration8                   1135
#define IDS_Duration9                   1136
#define IDS_Duration10                  1137
#define IDS_Duration11                  1138
#define IDS_Duration12                  1139
#define IDS_Duration13                  1140
#define IDS_Duration14                  1141
#define IDS_FirstContext                2000
#define IDS_LFContextStores             2000
#define IDS_LFContextStoreHome          2001
#define IDS_LFContextClipboard          2002
#define IDS_LFContextDefault            2003
#define IDS_LFContextSearch             2004
#define IDS_LFContextFilters            2005
#define IDS_LFContextHousekeeping       2006
#define IDS_LFContextTrash              2007
#define IDS_LFContextSubfolderDefault   2008
#define IDS_LFContextSubfolderDay       2009
#define IDS_LFContextSubfolderLocation  2010
#define IDS_FirstError                  3000
#define IDS_LFOk                        3000
#define IDS_LFCancel                    3001
#define IDS_LFErrorMemoryError          3002
#define IDS_LFErrorIllegalQuery         3003
#define IDS_LFErrorIllegalStoreDescriptor 3004
#define IDS_LFErrorStoreNotFound        3005
#define IDS_LFErrorDriveNotReady        3006
#define IDS_LFErrorDriveWriteProtected  3007
#define IDS_LFErrorIllegalPhysFolder    3008
#define IDS_LFErrorRegistryError        3009
#define IDS_LFErrorIllegalKey           3010
#define IDS_LFErrorNoDefaultStore       3011
#define IDS_LFErrorTooManyStores        3012
#define IDS_LFErrorStoreNotMounted      3013
#define IDS_LFErrorMutexError           3014
#define IDS_LFErrorIllegalAttribute     3015
#define IDS_LFErrorIllegalItemType      3016
#define IDS_LFErrorIllegalValue         3017
#define IDS_LFErrorIndexTableLoadError  3018
#define IDS_LFErrorIndexRepairError     3019
#define IDS_LFErrorIndexAccessError     3020
#define IDS_LFErrorIndexCreateError     3021
#define IDS_LFErrorNotEnoughFreeDisc    3022
#define IDS_LFErrorCannotImportFile     3023
#define IDS_LFErrorCannotDeleteFile     3024
#define IDS_LFErrorCannotRenameFile     3025
#define IDS_LFErrorCannotCopyIndex      3026
#define IDS_LFErrorNoFileBody           3027
#define IDS_FirstAttribute              4000
#define IDS_AttrFileName                4000
#define IDS_AttrStoreID                 4001
#define IDS_AttrFileID                  4002
#define IDS_AttrComments                4003
#define IDS_AttrDescription             4004
#define IDS_AttrCreationTime            4005
#define IDS_AttrFileTime                4006
#define IDS_AttrAddTime                 4007
#define IDS_AttrDeleteTime              4008
#define IDS_AttrArchiveTime             4009
#define IDS_AttrFileFormat              4010
#define IDS_AttrFileCount               4011
#define IDS_AttrFileSize                4012
#define IDS_AttrFlags                   4013
#define IDS_AttrURL                     4014
#define IDS_AttrTags                    4015
#define IDS_AttrRating                  4016
#define IDS_AttrPriority                4017
#define IDS_AttrLocationName            4018
#define IDS_AttrLocationIATA            4019
#define IDS_AttrLocationGPS             4020
#define IDS_AttrWidth                   4021
#define IDS_AttrHeight                  4022
#define IDS_AttrDimension               4023
#define IDS_AttrAspectRatio             4024
#define IDS_AttrVideoCodec              4025
#define IDS_AttrRoll                    4026
#define IDS_AttrExposure                4027
#define IDS_AttrFocus                   4028
#define IDS_AttrAperture                4029
#define IDS_AttrChip                    4030
#define IDS_AttrAlbum                   4031
#define IDS_AttrChannels                4032
#define IDS_AttrSamplerate              4033
#define IDS_AttrAudioCodec              4034
#define IDS_AttrDuration                4035
#define IDS_AttrBitrate                 4036
#define IDS_AttrArtist                  4037
#define IDS_AttrTitle                   4038
#define IDS_AttrCopyright               4039
#define IDS_AttrISBN                    4040
#define IDS_AttrLanguage                4041
#define IDS_AttrPages                   4042
#define IDS_AttrRecordingTime           4043
#define IDS_AttrRecordingEquipment      4044
#define IDS_AttrSignature               4045
#define IDS_AttrFrom                    4046
#define IDS_AttrTo                      4047
#define IDS_AttrResponsible             4048
#define IDS_AttrDueTime                 4049
#define IDS_AttrDoneTime                4050
#define IDS_AttrCustomer                4051
#define IDS_FirstDomain                 5000
#define IDS_DomainAllFiles              5000
#define IDS_DomainAllMediaFiles         5001
#define IDS_DomainFavorites             5002
#define IDS_DomainTrash                 5003
#define IDS_DomainUnknown               5004
#define IDS_DomainFilters               5005
#define IDS_DomainAudio                 5006
#define IDS_DomainPhotos                5007
#define IDS_DomainPictures              5008
#define IDS_DomainVideos                5009
#define IDS_DomainArchives              5010
#define IDS_DomainContacts              5011
#define IDS_DomainDocuments             5012
#define IDS_DomainEvents                5013
#define IDS_DomainFonts                 5014
#define IDS_DomainGeodata               5015
#define IDS_DomainMessages              5016
#define IDS_DomainPresentations         5017
#define IDS_DomainSpreadsheets          5018
#define IDS_DomainWeb                   5019
#define IDS_DefaultStore                6000
#define ID_VIEW_APPLOOK_OFF_2007_NONE   -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
