//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LFCore.rc
//
#define IDI_STR_LIQUIDFOLDERS           1
#define IDI_STR_WINDOWS                 2
#define IDI_STR_1394                    3
#define IDI_STR_USB                     4
#define IDI_STR_NETHOOD                 5
#define IDI_STR_BOX                     6
#define IDI_STR_DROPBOX                 7
#define IDI_STR_ICLOUDDRIVE             8
#define IDI_STR_ONEDRIVE                9
#define IDI_STR_ICLOUDPHOTOS            10
#define IDI_STR_GOOGLEDRIVE             11
#define IDI_STR_RESERVED5               12
#define IDI_STR_RESERVED4               13
#define IDI_STR_RESERVED3               14
#define IDI_STR_RESERVED2               15
#define IDI_STR_RESERVED1               16
#define IDI_FLD_DEFAULT                 17
#define IDI_FLD_RED                     18
#define IDI_FLD_ORANGE                  19
#define IDI_FLD_YELLOW                  20
#define IDI_FLD_GREEN                   21
#define IDI_FLD_BLUE                    22
#define IDI_FLD_PURPLE                  23
#define IDI_FLD_GRAY                    24
#define IDI_FLD_CONTENT                 25
#define IDI_FLD_DEFAULTGENRE            26
#define IDI_FLD_ALTERNATIVE             27
#define IDI_FLD_AMBIENT                 28
#define IDI_FLD_BLUES                   29
#define IDI_FLD_CLASSICAL               30
#define IDI_FLD_COUNTRY                 31
#define IDI_FLD_DANCE                   32
#define IDI_FLD_EASYLISTENING           33
#define IDI_FLD_ELECTRONIC              34
#define IDI_FLD_HIPHOP                  35
#define IDI_FLD_JAZZ                    36
#define IDI_FLD_JPOP                    37
#define IDI_FLD_LATIN                   38
#define IDI_FLD_METAL                   39
#define IDI_FLD_OLDIES                  40
#define IDI_FLD_POP                     41
#define IDI_FLD_RANDB                   42
#define IDI_FLD_REDCURTAIN              43
#define IDI_FLD_REGGAE                  44
#define IDI_FLD_ROCK                    45
#define IDI_FLD_SOUL                    46
#define IDI_FLD_SOUNDTRACKS             47
#define IDI_FLD_SPOKENWORD              48
#define IDI_FLD_WORLDMUSIC              49
#define IDI_APP_DEFAULT                 50
#define IDI_APP_BOOMERANG               51
#define IDI_APP_CINEMAGRAPH             52
#define IDI_APP_FACEBOOK                53
#define IDI_APP_HIPSTAMATIC             54
#define IDI_APP_HYPERLAPSE              55
#define IDI_APP_INCREDIBOOTH            56
#define IDI_APP_INSTAGRAM               57
#define IDI_APP_LABELBOX                58
#define IDI_APP_LAYOUT                  59
#define IDI_APP_PINTEREST               60
#define IDI_APP_RETRICA                 61
#define IDI_APP_SNAPCHAT                62
#define IDI_APP_VINTAGECAM              63
#define IDI_APP_VSCO                    64
#define IDI_APP_YOUTUBE                 65
#define IDI_APP_JODEL                   66
#define IDI_APP_VIMEO                   67
#define IDI_APP_PICFX                   68
#define IDI_APP_AFTERLIGHT              69
#define IDI_OVR_ERROR                   70
#define IDI_OVR_DEFAULT                 71
#define IDI_OVR_NEW                     72
#define IDI_OVR_EMPTY                   73
#define IDI_ROL_DEFAULT                 74
#define IDI_FLD_PLACEHOLDER_DEFAULT     75
#define IDI_FLD_PLACEHOLDER_CONTACT     76
#define IDI_FLD_PLACEHOLDER_LOCATION    77
#define IDI_FLD_PLACEHOLDER_NOTE        78
#define IDI_FLD_PLACEHOLDER_PODCAST     79
#define IDI_FLD_PLACEHOLDER_TV          80
#define IDI_LASTSTOREICON               16
#define IDI_FIRSTPLACEHOLDERICON        75
#define IDI_LASTICON                    80
#define IDS_NEWSTORE                    1000
#define IDS_LASTSEEN                    1001
#define IDS_FILESUMMARY_SINGULAR        1002
#define IDS_FILESUMMARY_PLURAL          1003
#define IDS_MEDIASUMMARY_SINGULAR       1004
#define IDS_MEDIASUMMARY_PLURAL         1005
#define IDS_MINUTE                      1006
#define IDS_MINUTES                     1007
#define IDS_HOUR                        1008
#define IDS_HOURS                       1009
#define IDS_ERRORCAPTION                1010
#define IDS_ALBUM                       1011
#define IDS_ARTIST                      1012
#define IDS_AUTHOR                      1013
#define IDS_EPISODE                     1014
#define IDS_PODCAST                     1015
#define IDS_ROLL                        1016
#define IDS_TRACK                       1017
#define IDS_TVSHOW                      1018
#define IDS_RATING1                     1111
#define IDS_RATING2                     1112
#define IDS_RATING3                     1113
#define IDS_RATING4                     1114
#define IDS_RATING5                     1115
#define IDS_PRIORITY1                   1116
#define IDS_PRIORITY2                   1117
#define IDS_PRIORITY3                   1118
#define IDS_PRIORITY4                   1119
#define IDS_PRIORITY5                   1120
#define IDS_SIZE1                       1121
#define IDS_SIZE2                       1122
#define IDS_SIZE3                       1123
#define IDS_SIZE4                       1124
#define IDS_SIZE5                       1125
#define IDS_SIZE6                       1126
#define IDS_COLOR1                      1127
#define IDS_COLOR2                      1128
#define IDS_COLOR3                      1129
#define IDS_COLOR4                      1130
#define IDS_COLOR5                      1131
#define IDS_COLOR6                      1132
#define IDS_COLOR7                      1133
#define IDS_DURATION1                   1134
#define IDS_DURATION2                   1135
#define IDS_DURATION3                   1136
#define IDS_DURATION4                   1137
#define IDS_DURATION5                   1138
#define IDS_DURATION6                   1139
#define IDS_DURATION7                   1140
#define IDS_DURATION8                   1141
#define IDS_DURATION9                   1142
#define IDS_DURATION10                  1143
#define IDS_DURATION11                  1144
#define IDS_DURATION12                  1145
#define IDS_DURATION13                  1146
#define IDS_DURATION14                  1147
#define IDS_CHANNELS1                   1148
#define IDS_CHANNELS2                   1149
#define IDS_CHANNELS3                   1150
#define IDS_ITEMCATEGORY_FIRST          1200
#define IDS_ITEMCATEGORY_LOCALSTORES    1200
#define IDS_ITEMCATEGORY_REMOTESTORES   1201
#define IDS_ATTRCATEGORY_FIRST          1300
#define IDS_ATTRCATEGORY_BASIC          1300
#define IDS_ATTRCATEGORY_MEDIA          1301
#define IDS_ATTRCATEGORY_VISUAL         1302
#define IDS_ATTRCATEGORY_AUDIO          1303
#define IDS_ATTRCATEGORY_DOCUMENTS      1304
#define IDS_ATTRCATEGORY_MESSAGES       1305
#define IDS_ATTRCATEGORY_TASKS          1306
#define IDS_ATTRCATEGORY_GEOTAGGING     1307
#define IDS_ATTRCATEGORY_INTERNAL       1308
#define IDS_CONTEXT_FIRST               1400
#define IDS_CONTEXT_ALLFILES            1400
#define IDS_CONTEXT_FILTERS             1401
#define IDS_CONTEXT_AUDIO               1402
#define IDS_CONTEXT_PICTURES            1403
#define IDS_CONTEXT_VIDEOS              1404
#define IDS_CONTEXT_DOCUMENTS           1405
#define IDS_CONTEXT_CONTACTS            1406
#define IDS_CONTEXT_MESSAGES            1407
#define IDS_CONTEXT_FONTS               1408
#define IDS_CONTEXT_APPS                1409
#define IDS_CONTEXT_BOOKS               1410
#define IDS_CONTEXT_MOVIES              1411
#define IDS_CONTEXT_MUSIC               1412
#define IDS_CONTEXT_PODCASTS            1413
#define IDS_CONTEXT_TVSHOWS             1414
#define IDS_CONTEXT_COLORTABLES         1415
#define IDS_CONTEXT_FAVORITES           1416
#define IDS_CONTEXT_NEW                 1417
#define IDS_CONTEXT_TASKS               1418
#define IDS_CONTEXT_ARCHIVE             1419
#define IDS_CONTEXT_TRASH               1420
#define IDS_CONTEXT_SEARCH              1421
#define IDS_CONTEXT_STORES              1422
#define IDS_CONTEXT_CLIPBOARD           1423
#define IDS_CONTEXT_SUBFOLDER_DEFAULT   1424
#define IDS_CONTEXT_SUBFOLDER_BOOKS     1425
#define IDS_CONTEXT_SUBFOLDER_FONTS     1426
#define IDS_CONTEXT_SUBFOLDER_MESSAGES  1427
#define IDS_CONTEXT_SUBFOLDER_MOVIES    1428
#define IDS_CONTEXT_SUBFOLDER_MUSIC     1429
#define IDS_CONTEXT_SUBFOLDER_PICTURES  1430
#define IDS_CONTEXT_SUBFOLDER_PODCASTS  1431
#define IDS_CONTEXT_SUBFOLDER_TVSHOWS   1432
#define IDS_CONTEXT_SUBFOLDER_VIDEOS    1433
#define IDS_ERR_FIRST                   1500
#define IDS_ERR_OK                      1500
#define IDS_ERR_CANCEL                  1501
#define IDS_ERR_DRIVEWRITEPROTECTED     1502
#define IDS_ERR_SHARINGVIOLATION1       1503
#define IDS_ERR_SHARINGVIOLATION2       1504
#define IDS_ERR_MEMORY                  1505
#define IDS_ERR_ILLEGALQUERY            1506
#define IDS_ERR_ILLEGALSTOREDESCRIPTOR  1507
#define IDS_ERR_STORENOTFOUND           1508
#define IDS_ERR_DRIVENOTREADY           1509
#define IDS_ERR_ILLEGALPHYSFOLDER       1510
#define IDS_ERR_REGISTRY                1511
#define IDS_ERR_NOACCESS                1512
#define IDS_ERR_ILLEGALID               1513
#define IDS_ERR_NODEFAULTSTORE          1514
#define IDS_ERR_TOOMANYSTORES           1515
#define IDS_ERR_STORENOTMOUNTED         1516
#define IDS_ERR_MUTEX                   1517
#define IDS_ERR_ILLEGALATTRIBUTE        1518
#define IDS_ERR_ILLEGALITEMTYPE         1519
#define IDS_ERR_ILLEGALVALUE            1520
#define IDS_ERR_INDEXLOAD               1521
#define IDS_ERR_INDEXREPAIR             1522
#define IDS_ERR_INDEXACCESS             1523
#define IDS_ERR_INDEXCREATE             1524
#define IDS_ERR_NOTENOUGHSPACE          1525
#define IDS_ERR_FILEWRITEPROTECTED      1526
#define IDS_ERR_CANNOTIMPORTFILE        1527
#define IDS_ERR_CANNOTDELETEFILE        1528
#define IDS_ERR_CANNOTRENAMEFILE        1529
#define IDS_ERR_INDEXCOPY               1530
#define IDS_ERR_NOFILEBODY              1531
#define IDS_ATTR_FIRST                  1600
#define IDS_ATTR_FILENAME               1600
#define IDS_ATTR_PRIORITY               1601
#define IDS_ATTR_CREATIONTIME           1602
#define IDS_ATTR_FILETIME               1603
#define IDS_ATTR_ADDTIME                1604
#define IDS_ATTR_DUETIME                1605
#define IDS_ATTR_DONETIME               1606
#define IDS_ATTR_ARCHIVETIME            1607
#define IDS_ATTR_DELETETIME             1608
#define IDS_ATTR_COLOR                  1609
#define IDS_ATTR_HASHTAGS               1610
#define IDS_ATTR_RATING                 1611
#define IDS_ATTR_COMMENTS               1612
#define IDS_ATTR_FILEFORMAT             1613
#define IDS_ATTR_FILECOUNT              1614
#define IDS_ATTR_FILESIZE               1615
#define IDS_ATTR_LOCATIONNAME           1616
#define IDS_ATTR_LOCATIONIATA           1617
#define IDS_ATTR_LOCATIONGPS            1618
#define IDS_ATTR_URL                    1619
#define IDS_ATTR_CREATOR                1620
#define IDS_ATTR_MEDIACOLLECTION        1621
#define IDS_ATTR_SEQUENCEINCOLLECTION   1622
#define IDS_ATTR_TITLE                  1623
#define IDS_ATTR_RELEASED          1624
#define IDS_ATTR_LENGTH               1625
#define IDS_ATTR_BITRATE                1626
#define IDS_ATTR_LANGUAGE               1627
#define IDS_ATTR_RECORDINGTIME          1628
#define IDS_ATTR_RECORDINGEQUIPMENT     1629
#define IDS_ATTR_COPYRIGHT              1630
#define IDS_ATTR_WIDTH                  1631
#define IDS_ATTR_HEIGHT                 1632
#define IDS_ATTR_DIMENSION              1633
#define IDS_ATTR_ASPECTRATIO            1634
#define IDS_ATTR_FRAMERATE              1635
#define IDS_ATTR_APPLICATION            1636
#define IDS_ATTR_VIDEOCODEC             1637
#define IDS_ATTR_EXPOSURE               1638
#define IDS_ATTR_FOCUS                  1639
#define IDS_ATTR_APERTURE               1640
#define IDS_ATTR_CHIP                   1641
#define IDS_ATTR_CHANNELS               1642
#define IDS_ATTR_SAMPLERATE             1643
#define IDS_ATTR_AUDIOCODEC             1644
#define IDS_ATTR_GENRE                  1645
#define IDS_ATTR_PAGES                  1646
#define IDS_ATTR_ISBN                   1647
#define IDS_ATTR_SIGNATURE              1648
#define IDS_ATTR_FROM                   1649
#define IDS_ATTR_TO                     1650
#define IDS_ATTR_RESPONSIBLE            1651
#define IDS_ATTR_CUSTOMER               1652
#define IDS_SRC_FIRST                   1700
#define IDS_SRC_UNKNOWN                 1700
#define IDS_SRC_LIQUIDFOLDERS           1701
#define IDS_SRC_WINDOWS                 1702
#define IDS_SRC_1394                    1703
#define IDS_SRC_USB                     1704
#define IDS_SRC_NETHOOD                 1705
#define IDS_SRC_BOX                     1706
#define IDS_SRC_DROPBOX                 1707
#define IDS_SRC_ICLOUDDRIVE             1708
#define IDS_SRC_ONEDRIVE                1709
#define IDS_SRC_ICLOUDPHOTOS            1710
#define IDS_SRC_GOOGLEDRIVE             1711
#define IDS_QSRC_FIRST                  1800
#define IDS_QSRC_UNKNOWN                1800
#define IDS_QSRC_LIQUIDFOLDERS          1801
#define IDS_QSRC_WINDOWS                1802
#define IDS_QSRC_1394                   1803
#define IDS_QSRC_USB                    1804
#define IDS_QSRC_NETHOOD                1805
#define IDS_QSRC_BOX                    1806
#define IDS_QSRC_DROPBOX                1807
#define IDS_QSRC_ICLOUDDRIVE            1808
#define IDS_QSRC_ONEDRIVE               1809
#define IDS_QSRC_ICLOUDPHOTOS           1810
#define IDS_QSRC_GOOGLEDRIVE            1811

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
