//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LFCore.rc
//
#define IDI_STR_Unknown                 1
#define IDI_STR_Internal                2
#define IDI_STR_1394                    3
#define IDI_STR_USB                     4
#define IDI_STR_Dropbox                 5
#define IDI_STR_Facebook                6
#define IDI_STR_Flickr                  7
#define IDI_STR_Instagram               8
#define IDI_STR_Pinterest               9
#define IDI_STR_SoundCloud              10
#define IDI_STR_Twitter                 11
#define IDI_STR_YouTube                 12
#define IDI_FLD_Default                 13
#define IDI_OVR_Default                 14
#define IDI_LastIcon                    14
#define IDS_FirstItemCategory           1000
#define IDS_LFCategoryLocalStores       1000
#define IDS_LFCategoryRemoteStores      1001
#define IDS_LFCategoryDrives            1002
#define IDS_LFCategoryNight             1003
#define IDS_FirstAttrCategory           1050
#define IDS_LFCategoryBasic             1050
#define IDS_LFCategoryGeotagging        1051
#define IDS_LFCategoryVisual            1052
#define IDS_LFCategoryPhotographic      1053
#define IDS_LFCategoryAudio             1054
#define IDS_LFCategoryTimebased         1055
#define IDS_LFCategoryBibliographic     1056
#define IDS_LFCategoryWorkflow          1057
#define IDS_LFCategoryInternal          1058
#define IDS_StoreDefaultName            1100
#define IDS_LastSeen                    1101
#define IDS_SeenOn                      1102
#define IDS_ErrorCaption                1103
#define IDS_DeleteStoreCaption          1104
#define IDS_DeleteStoreMessage          1105
#define IDS_ShortcutCaption             1106
#define IDS_ShortcutMessage             1107
#define IDS_HintSingular                1108
#define IDS_HintPlural                  1109
#define IDS_Rating1                     1110
#define IDS_Rating2                     1111
#define IDS_Rating3                     1112
#define IDS_Rating4                     1113
#define IDS_Rating5                     1114
#define IDS_Priority1                   1115
#define IDS_Priority2                   1116
#define IDS_Priority3                   1117
#define IDS_Priority4                   1118
#define IDS_Priority5                   1119
#define IDS_Size1                       1120
#define IDS_Size2                       1121
#define IDS_Size3                       1122
#define IDS_Size4                       1123
#define IDS_Size5                       1124
#define IDS_Size6                       1125
#define IDS_Duration1                   1126
#define IDS_Duration2                   1127
#define IDS_Duration3                   1128
#define IDS_Duration4                   1129
#define IDS_Duration5                   1130
#define IDS_Duration6                   1131
#define IDS_Duration7                   1132
#define IDS_Duration8                   1133
#define IDS_Duration9                   1134
#define IDS_Duration10                  1135
#define IDS_Duration11                  1136
#define IDS_Duration12                  1137
#define IDS_Duration13                  1138
#define IDS_Duration14                  1139
#define IDS_FirstContext                2000
#define IDS_LFContextAllFiles           2000
#define IDS_LFContextFavorites          2001
#define IDS_LFContextAudio              2002
#define IDS_LFContextPictures           2003
#define IDS_LFContextVideos             2004
#define IDS_LFContextDocuments          2005
#define IDS_LFContextContacts           2006
#define IDS_LFContextMessages           2007
#define IDS_LFContextEvents             2008
#define IDS_LFContextNew                2009
#define IDS_LFContextTrash              2010
#define IDS_LFContextFilters            2011
#define IDS_LFContextSearch             2012
#define IDS_LFContextStores             2013
#define IDS_LFContextClipboard          2014
#define IDS_LFContextSubfolderDefault   2015
#define IDS_LFContextSubfolderDay       2016
#define IDS_LFContextSubfolderLocation  2017
#define IDS_FirstError                  3000
#define IDS_LFOk                        3000
#define IDS_LFCancel                    3001
#define IDS_LFErrorMemoryError          3002
#define IDS_LFErrorIllegalQuery         3003
#define IDS_LFErrorIllegalStoreDescriptor 3004
#define IDS_LFErrorStoreNotFound        3005
#define IDS_LFErrorDriveNotReady        3006
#define IDS_LFErrorDriveWriteProtected  3007
#define IDS_LFErrorIllegalPhysFolder    3008
#define IDS_LFErrorRegistryError        3009
#define IDS_LFErrorIllegalKey           3010
#define IDS_LFErrorNoDefaultStore       3011
#define IDS_LFErrorTooManyStores        3012
#define IDS_LFErrorStoreNotMounted      3013
#define IDS_LFErrorMutexError           3014
#define IDS_LFErrorIllegalAttribute     3015
#define IDS_LFErrorIllegalItemType      3016
#define IDS_LFErrorIllegalValue         3017
#define IDS_LFErrorIndexTableLoadError  3018
#define IDS_LFErrorIndexRepairError     3019
#define IDS_LFErrorIndexAccessError     3020
#define IDS_LFErrorIndexCreateError     3021
#define IDS_LFErrorNotEnoughFreeDisc    3022
#define IDS_LFErrorCannotImportFile     3023
#define IDS_LFErrorCannotDeleteFile     3024
#define IDS_LFErrorCannotRenameFile     3025
#define IDS_LFErrorCannotCopyIndex      3026
#define IDS_LFErrorNoFileBody           3027
#define IDS_FirstAttribute              4000
#define IDS_AttrFileName                4000
#define IDS_AttrStoreID                 4001
#define IDS_AttrFileID                  4002
#define IDS_AttrComments                4003
#define IDS_AttrDescription             4004
#define IDS_AttrCreationTime            4005
#define IDS_AttrFileTime                4006
#define IDS_AttrAddTime                 4007
#define IDS_AttrDeleteTime              4008
#define IDS_AttrArchiveTime             4009
#define IDS_AttrFileFormat              4010
#define IDS_AttrFileCount               4011
#define IDS_AttrFileSize                4012
#define IDS_AttrFlags                   4013
#define IDS_AttrURL                     4014
#define IDS_AttrTags                    4015
#define IDS_AttrRating                  4016
#define IDS_AttrPriority                4017
#define IDS_AttrLocationName            4018
#define IDS_AttrLocationIATA            4019
#define IDS_AttrLocationGPS             4020
#define IDS_AttrWidth                   4021
#define IDS_AttrHeight                  4022
#define IDS_AttrDimension               4023
#define IDS_AttrAspectRatio             4024
#define IDS_AttrVideoCodec              4025
#define IDS_AttrRoll                    4026
#define IDS_AttrExposure                4027
#define IDS_AttrFocus                   4028
#define IDS_AttrAperture                4029
#define IDS_AttrChip                    4030
#define IDS_AttrAlbum                   4031
#define IDS_AttrChannels                4032
#define IDS_AttrSamplerate              4033
#define IDS_AttrAudioCodec              4034
#define IDS_AttrDuration                4035
#define IDS_AttrBitrate                 4036
#define IDS_AttrArtist                  4037
#define IDS_AttrTitle                   4038
#define IDS_AttrCopyright               4039
#define IDS_AttrISBN                    4040
#define IDS_AttrLanguage                4041
#define IDS_AttrPages                   4042
#define IDS_AttrRecordingTime           4043
#define IDS_AttrRecordingEquipment      4044
#define IDS_AttrSignature               4045
#define IDS_AttrFrom                    4046
#define IDS_AttrTo                      4047
#define IDS_AttrResponsible             4048
#define IDS_AttrDueTime                 4049
#define IDS_AttrDoneTime                4050
#define IDS_AttrCustomer                4051
#define IDS_FirstSource                 5000
#define IDS_SrcUnknown                  5000
#define IDS_SrcInternal                 5001
#define IDS_Src1394                     5002
#define IDS_SrcUSB                      5003
#define IDS_SrcDropbox                  5004
#define IDS_SrcFacebook                 5005
#define IDS_SrcFlickr                   5006
#define IDS_SrcInstagram                5007
#define IDS_SrcPinterest                5008
#define IDS_SrcSoundCloud               5009
#define IDS_SrcTwitter                  5010
#define IDS_SrcYouTube                  5011
#define IDS_FirstQualifiedSource        5100
#define IDS_QSrcUnknown                 5100
#define IDS_QSrcInternal                5101
#define IDS_QSrc1394                    5102
#define IDS_QSrcUSB                     5103
#define IDS_QSrcDropbox                 5104
#define IDS_QSrcFacebook                5105
#define IDS_QSrcFlickr                  5106
#define IDS_QSrcInstagram               5107
#define IDS_QSrcPinterest               5108
#define IDS_QSrcSoundCloud              5109
#define IDS_QSrcTwitter                 5110
#define IDS_QSrcYouTube                 5111
#define IDS_DefaultStore                6000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
