//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StoreManager.rc
//
#define SC_ALWAYSONTOP                  0x10
#define IDR_CLIPBOARD                   129
#define IDR_FILEDROP                    130
#define IDR_MIGRATIONWIZARD             131
#define IDB_TASKS_16                    132
#define IDB_TASKS_32                    133
#define IDB_ASCENDING                   134
#define IDB_DESCENDING                  135
#define IDB_GROUPING                    136
#define IDB_INSPECTOR                   137
#define IDB_MULTIPLE                    138
#define IDB_VIEWS                       139
#define IDB_CONTEXTS_16                 140
#define IDB_CONTEXTS_32                 141
#define IDB_GLOBEICONS_RGB              142
#define IDB_GLOBEICONS_ALPHA            143
#define IDB_BLUEMARBLE_1024             144
#define IDB_BLUEMARBLE_2048             145
#define IDB_BLUEMARBLE_4096             146
#define IDB_BLUEMARBLE_8192             147
#define IDB_JOURNAL_FRAME0              148
#define IDB_JOURNAL_FRAME1              149
#define IDB_JOURNAL_NORMAL0             150
#define IDB_JOURNAL_NORMAL1             151
#define IDB_JOURNAL_HOT0                152
#define IDB_JOURNAL_HOT1                153
#define IDB_JOURNAL_PRESSED0            154
#define IDB_JOURNAL_PRESSED1            155
#define IDB_JOURNAL_DISABLED0           156
#define IDB_JOURNAL_DISABLED1           157
#define IDB_THUMBNAIL_SHADOW            158
#define IDB_THUMBNAIL_FRAME             159
#define IDB_SOURCEICONS                 160
#define IDB_TREEWIDGETS                 161
#define ID_PANE_FILTER                  400
#define ID_PANE_INSPECTOR               401
#define ID_NAV_BACK                     500
#define ID_NAV_FORWARD                  501
#define ID_NAV_RELOAD                   502
#define IDS_VIEWGROUP1                  1000
#define IDS_VIEWGROUP2                  1001
#define IDS_CONTEXTMENU_SELECTALL       1002
#define IDS_CONTEXTMENU_SORTOPTIONS     1003
#define IDS_CONTEXTMENU_AUTODIRS        1004
#define IDS_CONTEXTMENU_VIEWOPTIONS     1005
#define IDS_CONTEXTMENU_OPEN            1006
#define IDS_CONTEXTMENU_OPENWITH        1007
#define IDS_CONTEXTMENU_OPENGOOGLEEARTH 1008
#define IDS_CONTEXTMENU_OPENBROWSER     1009
#define IDS_CONTEXTMENU_OPENNEWWINDOW   1010
#define IDS_CONTEXTMENU_OPENFILEDROP    1011
#define IDS_CONTEXTMENU_EDIT            1012
#define IDS_CONTEXTMENU_REMEMBER        1013
#define IDS_CONTEXTMENU_REMOVE          1014
#define IDS_CONTEXTMENU_SENDTO          1015
#define IDS_CONTEXTMENU_CHOOSESTORE     1016
#define IDS_CONTEXTMENU_ADDFILES        1017
#define IDS_CONTEXTMENU_IMPORTFOLDER    1018
#define IDS_CONTEXTMENU_MIGRATIONWIZARD 1019
#define IDS_CONTEXTMENU_MORE            1020
#define IDS_CONTEXTMENU_TIME            1021
#define IDS_CONTEXTMENU_LOCATION        1022
#define IDS_CONTEXTMENU_DIMENSION       1023
#define IDS_TXTFILEFILTER               1024
#define IDS_XMLFILEFILTER               1025
#define IDS_ATTRIBUTENOTSORTABLE        1026
#define IDS_NOITEMSSELECTED             1027
#define IDS_YOULOOKAT                   1028
#define IDS_NOTHINGTODISPLAY            1029
#define IDS_NONAVIGATION                1030
#define IDS_FORMAT_CAPTION              1031
#define IDS_FORMAT_TEXT                 1032
#define IDS_AUTOMATIC                   1033
#define IDS_ILLEGALYEAR                 1034
#define IDS_SUBFOLDERS_NOTAVAIL         1035
#define IDS_FILETYPES                   1036
#define IDS_HOUSEKEEPING                1037
#define IDS_SEARCHTERM                  1038
#define IDS_DROPTIP                     1039
#define IDS_NOROOT_CAPTION              1040
#define IDS_NOROOT_HINT                 1041
#define IDS_FOLDER_CAPTION              1042
#define IDS_FOLDER_HINT                 1043
#define IDS_STORE_CAPTION               1044
#define IDS_STORE_HINT                  1045
#define IDS_BROWSEFORFOLDER_CAPTION     1046
#define IDS_BROWSEFORFOLDER_HINT        1047
#define IDS_FOLDERCATEGORY1             1048
#define IDS_FOLDERCATEGORY2             1049
#define IDS_FOLDERCATEGORY3             1050
#define IDS_FOLDERCATEGORY4             1051
#define IDS_NOPROPERTY                  1052
#define IDS_CHOOSEPROPERTY              1053
#define IDS_EXPANDBRANCH                1054
#define IDS_INCLUDEBRANCH               1055
#define IDS_EXCLUDEBRANCH               1056
#define IDS_REPORTTAB0                  1057
#define IDS_REPORTTAB1                  1058
#define IDS_REPORTSTATUS_NOFILES        1059
#define IDS_REPORTSTATUS_ONEFILE        1060
#define IDS_REPORTSTATUS_FILES          1061
#define IDS_NOFOLDERS_CAPTION           1062
#define IDS_NOFOLDERS_MESSAGE           1063
#define IDS_VATTR_FIRST                 1100
#define IDS_VATTR_SOURCE                1100
#define IDS_VATTR_DRIVELETTER           1101
#define IDS_VATTR_MAINTENANCETIME       1102
#define IDS_VATTR_SYNCHRONIZETIME       1103
#define IDS_VATTR_LASTSEEN              1104
#define IDS_VATTR_IATA_NAME             1105
#define IDS_VATTR_IATA_COUNTRY          1106
#define IDD_CHOOSEDETAILS               2000
#define IDC_VIEWATTRIBUTES              2001
#define IDC_CHECKALL                    2002
#define IDC_UNCHECKALL                  2003
#define IDC_MOVEUP                      2004
#define IDC_MOVEDOWN                    2005
#define IDD_VIEWOPTIONS                 2050
#define IDC_VIEWMODES                   2051
#define IDD_SORTOPTIONS                 2100
#define IDC_SORTATTRIBUTE               2101
#define IDC_ASCENDING                   2102
#define IDC_DESCENDING                  2103
#define IDC_AUTODIRS                    2104
#define IDC_SUBFOLDERHINT               2105
#define IDD_GLOBEOPTIONS                2200
#define IDC_TEXTURESIZE                 2201
#define IDC_HQMODEL                     2202
#define IDC_LIGHTING                    2203
#define IDC_ATMOSPHERE                  2204
#define IDC_SPOTS                       2205
#define IDC_AIRPORTNAMES                2206
#define IDC_GPSCOORDINATES              2207
#define IDC_DESCRIPTION                 2208
#define IDC_VIEWPORT                    2209
#define IDC_CROSSHAIRS                  2210
#define IDD_GOTOYEAR                    2300
#define IDC_YEAR                        2301
#define IDD_EDITCONDITION               2400
#define IDC_COMPAREATTRIBUTE            2401
#define IDC_COMPARE                     2402
#define IDC_PROPERTY                    2403
#define IDD_EDITFILTER                  2500
#define IDC_ALLSTORES                   2501
#define IDC_THISSTORE                   2502
#define IDC_SEARCHTERM                  2503
#define IDC_CONDITIONLIST               2504
#define IDD_SAVEFILTER                  2600
#define IDC_DESTINATION                 2601
#define IDC_FILENAME                    2602
#define IDC_COMMENTS                    2603
#define IDD_BOTTOMAREA                  2700
#define IDC_MIGRATE                     2701
#define IDD_CHOOSEFOLDER                2800
#define IDC_EXPANDALL                   2801
#define IDD_CHOOSEPROPERTY              2900
#define IDC_ATTRIBUTES                  2901
#define IDD_DELETEFILES                 3000
#define IDD_MIGRATEREPORT               3100
#define IDC_FOLDERLIST                  3101
#define IDC_STATUS1                     3102
#define IDC_STATUS2                     3103
#define IDC_UNCHECKMIGRATED             3104
#define IDM_STORES_REPAIRCORRUPTEDINDEX 4000
#define IDM_NEW                         4100
#define IDM_NEW_REMOVENEW               4101
#define IDM_TRASH                       4200
#define IDM_TRASH_EMPTY                 4201
#define IDM_TRASH_RESTOREALL            4202
#define IDM_FILTERS                     4300
#define IDM_FILTERS_CREATENEW           4301
#define IDM_FILTERS_EDIT                4302
#define IDM_ITEM_OPEN                   4400
#define IDM_ITEM_OPENNEWWINDOW          4401
#define IDM_ITEM_OPENFILEDROP           4402
#define IDM_VOLUME                      4500
#define IDM_VOLUME_CREATENEWSTORE       4501
#define IDM_VOLUME_EJECT                4502
#define IDM_VOLUME_FORMAT               4503
#define IDM_VOLUME_PROPERTIES           4504
#define IDM_FILE                        4600
#define IDM_FILE_OPENWITH               4601
#define IDM_FILE_OPENBROWSER            4602
#define IDM_FILE_EDIT                   4603
#define IDM_FILE_REMEMBER               4604
#define IDM_FILE_REMOVE                 4605
#define IDM_FILE_ARCHIVE                4606
#define IDM_FILE_COPY                   4607
#define IDM_FILE_SHORTCUT               4608
#define IDM_FILE_DELETE                 4609
#define IDM_FILE_RENAME                 4610
#define IDM_FILE_PROPERTIES             4611
#define IDM_FILE_RESTORE                4612
#define IDM_FILE_AWAY                   4700
#define IDM_FOLDER                      4800
#define IDM_SELECTALL                   4900
#define IDM_SELECTNONE                  4901
#define IDM_SELECTINVERT                4902
#define IDM_DETAILS                     5000
#define IDM_DETAILS_AUTOSIZEALL         5001
#define IDM_DETAILS_AUTOSIZE            5002
#define IDM_DETAILS_CHOOSE              5003
#define IDM_DETAILS_TOGGLEATTRIBUTE     5004
#define IDM_CALENDAR                    5100
#define IDM_CALENDAR_SHOWCAPTIONS       5101
#define IDM_CALENDAR_PREVYEAR           5102
#define IDM_CALENDAR_NEXTYEAR           5103
#define IDM_CALENDAR_GOTOYEAR           5104
#define IDM_GLOBE                       5200
#define IDM_GLOBE_JUMPTOLOCATION        5201
#define IDM_GLOBE_ZOOMIN                5202
#define IDM_GLOBE_ZOOMOUT               5203
#define IDM_GLOBE_AUTOSIZE              5204
#define IDM_GLOBE_SETTINGS              5205
#define IDM_GLOBE_GOOGLEEARTH           5206
#define IDM_TAGCLOUD                    5300
#define IDM_TAGCLOUD_SORTVALUE          5301
#define IDM_TAGCLOUD_SORTCOUNT          5302
#define IDM_TAGCLOUD_SHOWRARE           5303
#define IDM_TAGCLOUD_USESIZE            5304
#define IDM_TAGCLOUD_USECOLORS          5305
#define IDM_TAGCLOUD_USEOPACITY         5306
#define IDM_TAGCLOUD_SORT               5307
#define IDM_NAV_SWITCHCONTEXT           5400
#define IDM_INSPECTOR                   5500
#define IDM_INSPECTOR_SHOWINTERNAL      5501
#define IDM_INSPECTOR_SORTALPHABETIC    5502
#define IDM_INSPECTOR_EXPORTSUMMARY     5503
#define IDM_INSPECTOR_EXPORTMETADATA    5504
#define IDM_CONDITIONLIST               5600
#define IDM_CONDITIONLIST_ADD           5601
#define IDM_MIGRATION_SELECTROOT        5700
#define IDM_TREE                        5800
#define IDM_TREEHEADER                  5801
#define IDM_TREE_SELECTROOT             5802
#define IDM_TREE_OPEN                   5803
#define IDM_TREE_DELETE                 5804
#define IDM_TREE_RENAME                 5805
#define IDM_TREE_PROPERTIES             5806
#define IDM_TREE_AUTOSIZEALL            5807
#define IDM_TREE_EXPAND                 5808
#define IDM_TREE_AUTOSIZE               5809
#define IDM_TREE_EXPANDCOLUMN           5810
#define IDM_TREE_EXPANDBRANCH           5811
#define IDM_TREE_CHOOSEPROPERTY         5812
#define IDM_TREE_RESETPROPERTY          5813
#define IDM_ORGANIZE                    6000
#define IDM_ORGANIZE_OPTIONS            6001
#define IDM_ORGANIZE_TOGGLEAUTODIRS     6002
#define IDM_ORGANIZE_FIRST              6003
#define IDM_VIEW                        7000
#define IDM_VIEW_OPTIONS                7001
#define IDM_VIEW_FIRST                  7002
#define IDM_VIEW_LARGEICONS             7002
#define IDM_VIEW_SMALLICONS             7003
#define IDM_VIEW_LIST                   7004
#define IDM_VIEW_DETAILS                7005
#define IDM_VIEW_TILES                  7006
#define IDM_VIEW_STRIPS                 7007
#define IDM_VIEW_CONTENT                7008
#define IDM_VIEW_PREVIEW                7009
#define IDM_VIEW_CALENDAR               7010
#define IDM_VIEW_TIMELINE               7011
#define IDM_VIEW_GLOBE                  7012
#define IDM_VIEW_TAGCLOUD               7013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8011
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         8025
#define _APS_NEXT_SYMED_VALUE           8007
#endif
#endif
