//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StoreManager.rc
//
#define IDR_APPLICATION                 128
#define IDR_CLIPBOARD                   129
#define IDB_ABOUTICON                   130
#define IDB_TASKS                       131
#define IDB_ASCENDING                   132
#define IDB_DESCENDING                  133
#define IDB_GROUPING                    134
#define IDB_INSPECTOR                   135
#define IDB_MULTIPLE                    136
#define IDB_VIEWS                       137
#define IDB_CONTEXTS_16                 138
#define IDB_CONTEXTS_32                 139
#define IDB_GLOBEICONS_RGB              140
#define IDB_GLOBEICONS_ALPHA            141
#define IDB_BLUEMARBLE_1024             142
#define IDB_BLUEMARBLE_2048             143
#define IDB_BLUEMARBLE_4096             144
#define IDB_BLUEMARBLE_8192             145
#define IDB_JOURNAL_FRAME0              146
#define IDB_JOURNAL_FRAME1              147
#define IDB_JOURNAL_NORMAL0             148
#define IDB_JOURNAL_NORMAL1             149
#define IDB_JOURNAL_HOT0                150
#define IDB_JOURNAL_HOT1                151
#define IDB_JOURNAL_PRESSED0            152
#define IDB_JOURNAL_PRESSED1            153
#define IDB_JOURNAL_DISABLED0           154
#define IDB_JOURNAL_DISABLED1           155
#define IDB_THUMBNAIL_SHADOW            156
#define IDB_THUMBNAIL_FRAME             157
#define IDB_SOURCEICONS                 158
#define ID_PANE_FILTER                  400
#define ID_PANE_INSPECTOR               401
#define ID_NAV_BACK                     500
#define ID_NAV_FORWARD                  501
#define ID_NAV_RELOAD                   502
#define IDS_VIEWGROUP1                  1000
#define IDS_VIEWGROUP2                  1001
#define IDS_CONTEXTMENU_SELECTALL       1002
#define IDS_CONTEXTMENU_SORTOPTIONS     1003
#define IDS_CONTEXTMENU_AUTODIRS        1004
#define IDS_CONTEXTMENU_VIEWOPTIONS     1005
#define IDS_CONTEXTMENU_OPEN            1006
#define IDS_CONTEXTMENU_OPENWITH        1007
#define IDS_CONTEXTMENU_OPENGOOGLEEARTH 1008
#define IDS_CONTEXTMENU_OPENNEWWINDOW   1009
#define IDS_CONTEXTMENU_EDIT            1010
#define IDS_CONTEXTMENU_REMEMBER        1011
#define IDS_CONTEXTMENU_REMOVE          1012
#define IDS_CONTEXTMENU_SENDTO          1013
#define IDS_CONTEXTMENU_CHOOSESTORE     1014
#define IDS_CONTEXTMENU_IMPORTFOLDER    1015
#define IDS_CONTEXTMENU_MORE            1016
#define IDS_CONTEXTMENU_TIME            1017
#define IDS_CONTEXTMENU_LOCATION        1018
#define IDS_CONTEXTMENU_DIMENSION       1019
#define IDS_TXTFILEFILTER               1020
#define IDS_XMLFILEFILTER               1021
#define IDS_ATTRIBUTENOTSORTABLE        1022
#define IDS_NOITEMSSELECTED             1023
#define IDS_YOULOOKAT                   1024
#define IDS_NOTHINGTODISPLAY            1025
#define IDS_NONAVIGATION                1026
#define IDS_FORMAT_CAPTION              1027
#define IDS_FORMAT_TEXT                 1028
#define IDS_AUTOMATIC                   1029
#define IDS_ILLEGALYEAR                 1030
#define IDS_LEGEND                      1031
#define IDS_LEGEND_RED                  1032
#define IDS_SUBFOLDERS_NOTAVAIL         1033
#define IDS_FILETYPES                   1034
#define IDS_HOUSEKEEPING                1035
#define IDS_SEARCHTERM                  1036
#define IDS_VATTR_FIRST                 1100
#define IDS_VATTR_SOURCE                1100
#define IDS_VATTR_DRIVELETTER           1101
#define IDS_VATTR_MAINTENANCETIME       1102
#define IDS_VATTR_LASTSEEN              1103
#define IDS_VATTR_IATA_NAME             1104
#define IDS_VATTR_IATA_COUNTRY          1105
#define IDD_CHOOSEDETAILS               2000
#define IDC_VIEWATTRIBUTES              2001
#define IDC_CHECKALL                    2002
#define IDC_UNCHECKALL                  2003
#define IDC_MOVEUP                      2004
#define IDC_MOVEDOWN                    2005
#define IDD_VIEWOPTIONS                 2050
#define IDC_VIEWMODES                   2051
#define IDD_SORTOPTIONS                 2100
#define IDC_SORTATTRIBUTE               2101
#define IDC_ASCENDING                   2102
#define IDC_DESCENDING                  2103
#define IDC_AUTODIRS                    2104
#define IDC_SUBFOLDERHINT               2105
#define IDD_GLOBEOPTIONS                2200
#define IDC_TEXTURESIZE                 2201
#define IDC_HQMODEL                     2202
#define IDC_LIGHTING                    2203
#define IDC_ATMOSPHERE                  2204
#define IDC_SPOTS                       2205
#define IDC_AIRPORTNAMES                2206
#define IDC_GPSCOORDINATES              2207
#define IDC_DESCRIPTION                 2208
#define IDC_VIEWPORT                    2209
#define IDC_CROSSHAIRS                  2210
#define IDD_GOTOYEAR                    2300
#define IDC_YEAR                        2301
#define IDD_EDITCONDITION               2400
#define IDC_COMPAREATTRIBUTE            2401
#define IDC_COMPARE                     2402
#define IDC_PROPERTY                    2403
#define IDD_EDITFILTER                  2500
#define IDC_ALLSTORES                   2501
#define IDC_THISSTORE                   2502
#define IDC_SEARCHTERM                  2503
#define IDC_CONDITIONLIST               2504
#define IDD_SAVEFILTER                  2600
#define IDC_FILENAME                    2601
#define IDC_COMMENTS                    2602
#define IDM_STORES_REPAIRCORRUPTEDINDEX 3000
#define IDM_NEW                         3100
#define IDM_NEW_REMOVENEW               3101
#define IDM_TRASH                       3200
#define IDM_TRASH_RESTOREALL            3201
#define IDM_TRASH_EMPTY                 3202
#define IDM_FILTERS                     3300
#define IDM_FILTERS_CREATENEW           3301
#define IDM_FILTERS_EDIT                3302
#define IDM_ITEM_OPEN                   3400
#define IDM_ITEM_OPENNEWWINDOW          3401
#define IDM_VOLUME                      3500
#define IDM_VOLUME_CREATENEWSTORE       3501
#define IDM_VOLUME_EJECT                3502
#define IDM_VOLUME_FORMAT               3503
#define IDM_VOLUME_PROPERTIES           3504
#define IDM_FILE                        3600
#define IDM_FILE_OPENWITH               3601
#define IDM_FILE_EDIT                   3602
#define IDM_FILE_REMEMBER               3603
#define IDM_FILE_REMOVE                 3604
#define IDM_FILE_ARCHIVE                3605
#define IDM_FILE_COPY                   3606
#define IDM_FILE_SHORTCUT               3607
#define IDM_FILE_DELETE                 3608
#define IDM_FILE_RENAME                 3609
#define IDM_FILE_RESTORE                3700
#define IDM_FILE_AWAY                   3800
#define IDM_FOLDER                      3900
#define IDM_SELECTALL                   4000
#define IDM_SELECTNONE                  4001
#define IDM_SELECTINVERT                4002
#define IDM_DETAILS                     4100
#define IDM_DETAILS_AUTOSIZEALL         4101
#define IDM_DETAILS_AUTOSIZE            4102
#define IDM_DETAILS_CHOOSE              4103
#define IDM_DETAILS_TOGGLEATTRIBUTE     4104
#define IDM_CALENDAR                    4200
#define IDM_CALENDAR_SHOWCAPTIONS       4201
#define IDM_CALENDAR_PREVYEAR           4202
#define IDM_CALENDAR_NEXTYEAR           4203
#define IDM_CALENDAR_GOTOYEAR           4204
#define IDM_GLOBE                       4300
#define IDM_GLOBE_JUMPTOLOCATION        4301
#define IDM_GLOBE_ZOOMIN                4302
#define IDM_GLOBE_ZOOMOUT               4303
#define IDM_GLOBE_AUTOSIZE              4304
#define IDM_GLOBE_SETTINGS              4305
#define IDM_GLOBE_GOOGLEEARTH           4306
#define IDM_TAGCLOUD                    4400
#define IDM_TAGCLOUD_SORTVALUE          4401
#define IDM_TAGCLOUD_SORTCOUNT          4402
#define IDM_TAGCLOUD_SHOWRARE           4403
#define IDM_TAGCLOUD_USESIZE            4404
#define IDM_TAGCLOUD_USECOLORS          4405
#define IDM_TAGCLOUD_USEOPACITY         4406
#define IDM_TAGCLOUD_SORT               4407
#define IDM_NAV_SWITCHCONTEXT           4500
#define IDM_INSPECTOR                   4600
#define IDM_INSPECTOR_SHOWPREVIEW       4601
#define IDM_INSPECTOR_SHOWINTERNAL      4602
#define IDM_INSPECTOR_SORTALPHABETIC    4603
#define IDM_INSPECTOR_EXPORTSUMMARY     4604
#define IDM_INSPECTOR_EXPORTMETADATA    4605
#define IDM_CONDITIONLIST               4700
#define IDM_CONDITIONLIST_ADD           4701
#define IDM_ORGANIZE                    5000
#define IDM_ORGANIZE_OPTIONS            5001
#define IDM_ORGANIZE_TOGGLEAUTODIRS     5002
#define IDM_ORGANIZE_FIRST              5003
#define IDM_VIEW                        6000
#define IDM_VIEW_OPTIONS                6001
#define IDM_VIEW_FIRST                  6002
#define IDM_VIEW_LARGEICONS             6002
#define IDM_VIEW_SMALLICONS             6003
#define IDM_VIEW_LIST                   6004
#define IDM_VIEW_DETAILS                6005
#define IDM_VIEW_TILES                  6006
#define IDM_VIEW_STRIPS                 6007
#define IDM_VIEW_CONTENT                6008
#define IDM_VIEW_PREVIEW                6009
#define IDM_VIEW_CALENDAR               6010
#define IDM_VIEW_TIMELINE               6011
#define IDM_VIEW_GLOBE                  6012
#define IDM_VIEW_TAGCLOUD               6013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8011
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         8025
#define _APS_NEXT_SYMED_VALUE           8007
#endif
#endif
