//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by liquidFOLDERS.rc
//
#define SC_ALWAYSONTOP                  0x10
#define IDB_CONTEXTS_16                 130
#define IDB_CONTEXTS_24                 131
#define IDB_CONTEXTS_32                 132
#define IDB_CONTEXTS_48                 133
#define IDB_CONTEXTS_64                 134
#define IDB_TASKS_16                    135
#define IDB_TASKS_24                    136
#define IDB_TASKS_32                    137
#define IDB_TASKS_48                    138
#define IDB_TASKS_64                    139
#define IDB_MULTIPLE                    140
#define IDB_THUMBNAIL                   141
#define IDB_BLUEMARBLE_512              142
#define IDB_APPLICATIONS_29             143
#define IDB_BACKGROUND_CAPACITYBAR      144
#define ID_PANE_INSPECTOR               400
#define ID_NAV_BACK                     500
#define ID_NAV_FORWARD                  501
#define ID_NAV_RELOAD                   502
#define IDS_CONTEXTMENU_AUTODIRS        1000
#define IDS_CONTEXTMENU_SELECTALL       1001
#define IDS_CONTEXTMENU_OPEN            1002
#define IDS_CONTEXTMENU_OPENWITH        1003
#define IDS_CONTEXTMENU_SHOWEXPLORER    1004
#define IDS_CONTEXTMENU_OPENGOOGLEEARTH 1005
#define IDS_CONTEXTMENU_OPENNEWWINDOW   1006
#define IDS_CONTEXTMENU_OPENFILEDROP    1007
#define IDS_CONTEXTMENU_SHOWCAPACITY    1008
#define IDS_CONTEXTMENU_EDIT            1009
#define IDS_CONTEXTMENU_SENDTO          1010
#define IDS_CONTEXTMENU_CHOOSESTORE     1011
#define IDS_CONTEXTMENU_MOVETO          1012
#define IDS_CONTEXTMENU_MOVETOCONTEXT   1013
#define IDS_CONTEXTMENU_REMOVEFROMCONTEXT 1014
#define IDS_CONTEXTMENU_REMEMBER        1015
#define IDS_CONTEXTMENU_REMOVEFROMCLIPBOARD 1016
#define IDS_CONTEXTMENU_MAKETASK        1017
#define IDS_CONTEXTMENU_TASKDONE        1018
#define IDS_CONTEXTMENU_MORE            1019
#define IDS_NOITEMSSELECTED             1020
#define IDS_NOTHINGTODISPLAY            1021
#define IDS_NORENDERINGCONTEXT          1022
#define IDS_FILETYPES                   1023
#define IDS_HOUSEKEEPING                1024
#define IDS_SEARCHTERM                  1025
#define IDS_STORE                       1026
#define IDS_DEFAULTSTORE                1027
#define IDS_FILESCOPIED                 1028
#define IDS_SHORTCUTCREATED             1029
#define IDS_QUALITY_LOW                 1030
#define IDS_QUALITY_MEDIUM              1031
#define IDS_QUALITY_HIGH                1032
#define IDS_QUALITY_ULTRA               1033
#define IDS_VATTR_FIRST                 1100
#define IDS_VATTR_FLAGS                 1100
#define IDS_VATTR_SOURCE                1101
#define IDS_VATTR_TOTALBYTES            1102
#define IDS_VATTR_TOTALBYTESFREE        1103
#define IDS_VATTR_FREEBYTESAVAILABLE    1104
#define IDS_VATTR_MAINTENANCETIME       1105
#define IDS_VATTR_SYNCHRONIZETIME       1106
#define IDS_VATTR_LASTSEEN              1107
#define IDS_VATTR_IATA_NAME             1108
#define IDS_VATTR_IATA_COUNTRY          1109
#define IDD_CHOOSEDETAILS               2000
#define IDC_VIEWATTRIBUTES              2001
#define IDC_CHECKALL                    2002
#define IDC_UNCHECKALL                  2003
#define IDC_MOVEUP                      2004
#define IDC_MOVEDOWN                    2005
#define IDD_ORGANIZE                    2100
#define IDC_SORTATTRIBUTE               2101
#define IDC_SORTDIRECTION               2102
#define IDD_GLOBEOPTIONS                2200
#define IDC_MODELQUALITY                2201
#define IDC_TEXTUREQUALITY              2202
#define IDC_TEXTURECOMPRESS             2203
#define IDC_SPOTS                       2204
#define IDC_AIRPORTNAMES                2205
#define IDC_GPSCOORDINATES              2206
#define IDC_DESCRIPTION                 2207
#define IDM_FONTS                       4000
#define IDM_FONTS_SHOWINSTALLED         4001
#define IDM_NEW                         4100
#define IDM_NEW_CLEARNEW                4101
#define IDM_TRASH                       4200
#define IDM_TRASH_EMPTY                 4201
#define IDM_TRASH_RECOVERALL            4202
#define IDM_FILTERS                     4300
#define IDM_FILTERS_CREATENEW           4301
#define IDM_FILTERS_EDIT                4302
#define IDM_ITEM_OPEN                   4400
#define IDM_FILE                        4500
#define IDM_FILE_OPENWITH               4501
#define IDM_FILE_SHOWEXPLORER           4502
#define IDM_FILE_EDIT                   4503
#define IDM_FILE_REMEMBER               4504
#define IDM_FILE_REMOVEFROMCLIPBOARD    4505
#define IDM_FILE_MAKETASK               4506
#define IDM_FILE_ARCHIVE                4507
#define IDM_FILE_COPY                   4508
#define IDM_FILE_SHORTCUT               4509
#define IDM_FILE_DELETE                 4510
#define IDM_FILE_RENAME                 4511
#define IDM_FILE_PROPERTIES             4512
#define IDM_FILE_TASKDONE               4513
#define IDM_FILE_RECOVER                4514
#define IDM_FILE_AWAY                   4600
#define IDM_SELECTALL                   4800
#define IDM_SELECTNONE                  4801
#define IDM_SELECTINVERT                4802
#define IDM_LIST                        4900
#define IDM_LIST_AUTOSIZEALL            4901
#define IDM_LIST_AUTOSIZE               4902
#define IDM_LIST_CHOOSE                 4903
#define IDM_LIST_TOGGLEATTRIBUTE        4904
#define IDM_ICONS                       5000
#define IDM_ICONS_SHOWCAPACITY          5001
#define IDM_CALENDAR                    5100
#define IDM_CALENDAR_SHOWDAYS           5101
#define IDM_CALENDAR_PREVYEAR           5102
#define IDM_CALENDAR_NEXTYEAR           5103
#define IDM_CALENDAR_GOTOYEAR           5104
#define IDM_GLOBE                       5200
#define IDM_GLOBE_JUMPTOLOCATION        5201
#define IDM_GLOBE_ZOOMIN                5202
#define IDM_GLOBE_ZOOMOUT               5203
#define IDM_GLOBE_AUTOSIZE              5204
#define IDM_GLOBE_SETTINGS              5205
#define IDM_GLOBE_GOOGLEEARTH           5206
#define IDM_TAGCLOUD                    5300
#define IDM_TAGCLOUD_SORTVALUE          5301
#define IDM_TAGCLOUD_SORTCOUNT          5302
#define IDM_TAGCLOUD_SHOWRARE           5303
#define IDM_TAGCLOUD_USESIZE            5304
#define IDM_TAGCLOUD_USECOLORS          5305
#define IDM_TAGCLOUD_USEOPACITY         5306
#define IDM_NAV_SWITCHCONTEXT           5400
#define IDM_INSPECTOR                   5500
#define IDM_INSPECTOR_SHOWINTERNAL      5501
#define IDM_INSPECTOR_SORTALPHABETIC    5502
#define IDM_ORGANIZE                    6000
#define IDM_ORGANIZE_OPTIONS            6001
#define IDM_ORGANIZE_FIRST              6002
#define IDM_VIEW                        7000
#define IDM_VIEW_FIRST                  7001
#define IDM_VIEW_ICONS                  7001
#define IDM_VIEW_LIST                   7002
#define IDM_VIEW_DETAILS                7003
#define IDM_VIEW_CALENDAR               7004
#define IDM_VIEW_TIMELINE               7005
#define IDM_VIEW_GLOBE                  7006
#define IDM_VIEW_TAGCLOUD               7007
#define IDM_FILE_MOVETOCONTEXT          8000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8011
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         8026
#define _APS_NEXT_SYMED_VALUE           8007
#endif
#endif
