//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by liquidFOLDERS.rc
//
#define SC_ALWAYSONTOP                  0x10
#define IDB_TASKS_16                    130
#define IDB_TASKS_32                    131
#define IDB_GLOBEICONS_RGB              132
#define IDB_GLOBEICONS_ALPHA            133
#define IDB_BLUEMARBLE_1024             134
#define IDB_BLUEMARBLE_2048             135
#define IDB_BLUEMARBLE_4096             136
#define IDB_BLUEMARBLE_8192             137
#define IDB_JOURNAL_FRAME0              138
#define IDB_JOURNAL_FRAME1              139
#define IDB_JOURNAL_NORMAL0             140
#define IDB_JOURNAL_NORMAL1             141
#define IDB_JOURNAL_HOT0                142
#define IDB_JOURNAL_HOT1                143
#define IDB_JOURNAL_PRESSED0            144
#define IDB_JOURNAL_PRESSED1            145
#define IDB_JOURNAL_DISABLED0           146
#define IDB_JOURNAL_DISABLED1           147
#define IDB_MULTIPLE                    148
#define IDB_CONTEXTS_16                 149
#define IDB_CONTEXTS_32                 150
#define IDB_THUMBNAIL_SHADOW            151
#define IDB_THUMBNAIL_FRAME             152
#define IDB_SOURCEICONS                 153
#define ID_PANE_FILTER                  400
#define ID_PANE_INSPECTOR               401
#define ID_NAV_BACK                     500
#define ID_NAV_FORWARD                  501
#define ID_NAV_RELOAD                   502
#define IDS_CONTEXTMENU_AUTODIRS        1000
#define IDS_CONTEXTMENU_SELECTALL       1001
#define IDS_CONTEXTMENU_OPEN            1002
#define IDS_CONTEXTMENU_OPENWITH        1003
#define IDS_CONTEXTMENU_OPENGOOGLEEARTH 1004
#define IDS_CONTEXTMENU_OPENBROWSER     1005
#define IDS_CONTEXTMENU_OPENNEWWINDOW   1006
#define IDS_CONTEXTMENU_OPENFILEDROP    1007
#define IDS_CONTEXTMENU_EDIT            1008
#define IDS_CONTEXTMENU_REMEMBER        1009
#define IDS_CONTEXTMENU_REMOVE          1010
#define IDS_CONTEXTMENU_SENDTO          1011
#define IDS_CONTEXTMENU_CHOOSESTORE     1012
#define IDS_CONTEXTMENU_IMPORTFOLDER    1013
#define IDS_CONTEXTMENU_MORE            1014
#define IDS_CONTEXTMENU_TIME            1015
#define IDS_CONTEXTMENU_LOCATION        1016
#define IDS_CONTEXTMENU_DIMENSION       1017
#define IDS_TXTFILEFILTER               1018
#define IDS_XMLFILEFILTER               1019
#define IDS_ATTRIBUTENOTSORTABLE        1020
#define IDS_NOITEMSSELECTED             1021
#define IDS_YOULOOKAT                   1022
#define IDS_NOTHINGTODISPLAY            1023
#define IDS_NONAVIGATION                1024
#define IDS_AUTOMATIC                   1025
#define IDS_FILETYPES                   1026
#define IDS_HOUSEKEEPING                1027
#define IDS_SEARCHTERM                  1028
#define IDS_DROPTIP                     1029
#define IDS_ASCENDING                   1030
#define IDS_DESCENDING                  1031
#define IDS_DEFAULTSTORE                1032
#define IDS_VATTR_FIRST                 1100
#define IDS_VATTR_SOURCE                1100
#define IDS_VATTR_MAINTENANCETIME       1101
#define IDS_VATTR_SYNCHRONIZETIME       1102
#define IDS_VATTR_LASTSEEN              1103
#define IDS_VATTR_IATA_NAME             1104
#define IDS_VATTR_IATA_COUNTRY          1105
#define IDD_CHOOSEDETAILS               2000
#define IDC_VIEWATTRIBUTES              2001
#define IDC_CHECKALL                    2002
#define IDC_UNCHECKALL                  2003
#define IDC_MOVEUP                      2004
#define IDC_MOVEDOWN                    2005
#define IDD_ORGANIZE                    2100
#define IDC_SORTATTRIBUTE               2101
#define IDC_AUTODIRS                    2102
#define IDC_SORTDIRECTION               2103
#define IDD_GLOBEOPTIONS                2200
#define IDC_TEXTURESIZE                 2201
#define IDC_HQMODEL                     2202
#define IDC_LIGHTING                    2203
#define IDC_ATMOSPHERE                  2204
#define IDC_SPOTS                       2205
#define IDC_AIRPORTNAMES                2206
#define IDC_GPSCOORDINATES              2207
#define IDC_DESCRIPTION                 2208
#define IDC_VIEWPORT                    2209
#define IDC_CROSSHAIRS                  2210
#define IDM_STORES_REPAIRCORRUPTEDINDEX 4000
#define IDM_NEW                         4100
#define IDM_NEW_CLEARNEW                4101
#define IDM_TRASH                       4200
#define IDM_TRASH_EMPTY                 4201
#define IDM_TRASH_RESTOREALL            4202
#define IDM_FILTERS                     4300
#define IDM_FILTERS_CREATENEW           4301
#define IDM_FILTERS_EDIT                4302
#define IDM_ITEM_OPEN                   4400
#define IDM_ITEM_OPENNEWWINDOW          4401
#define IDM_ITEM_OPENFILEDROP           4402
#define IDM_FILE                        4500
#define IDM_FILE_OPENWITH               4501
#define IDM_FILE_OPENBROWSER            4502
#define IDM_FILE_EDIT                   4503
#define IDM_FILE_REMEMBER               4504
#define IDM_FILE_REMOVE                 4505
#define IDM_FILE_ARCHIVE                4506
#define IDM_FILE_COPY                   4507
#define IDM_FILE_SHORTCUT               4508
#define IDM_FILE_DELETE                 4509
#define IDM_FILE_RENAME                 4510
#define IDM_FILE_PROPERTIES             4511
#define IDM_FILE_RESTORE                4512
#define IDM_FILE_AWAY                   4600
#define IDM_FOLDER                      4700
#define IDM_SELECTALL                   4800
#define IDM_SELECTNONE                  4801
#define IDM_SELECTINVERT                4802
#define IDM_DETAILS                     4900
#define IDM_DETAILS_AUTOSIZEALL         4901
#define IDM_DETAILS_AUTOSIZE            4902
#define IDM_DETAILS_CHOOSE              4903
#define IDM_DETAILS_TOGGLEATTRIBUTE     4904
#define IDM_CALENDAR                    5000
#define IDM_CALENDAR_SHOWCAPTIONS       5001
#define IDM_CALENDAR_PREVYEAR           5002
#define IDM_CALENDAR_NEXTYEAR           5003
#define IDM_CALENDAR_GOTOYEAR           5004
#define IDM_GLOBE                       5100
#define IDM_GLOBE_JUMPTOLOCATION        5101
#define IDM_GLOBE_ZOOMIN                5102
#define IDM_GLOBE_ZOOMOUT               5103
#define IDM_GLOBE_AUTOSIZE              5104
#define IDM_GLOBE_SETTINGS              5105
#define IDM_GLOBE_GOOGLEEARTH           5106
#define IDM_TAGCLOUD                    5200
#define IDM_TAGCLOUD_SORTVALUE          5201
#define IDM_TAGCLOUD_SORTCOUNT          5202
#define IDM_TAGCLOUD_SHOWRARE           5203
#define IDM_TAGCLOUD_USESIZE            5204
#define IDM_TAGCLOUD_USECOLORS          5205
#define IDM_TAGCLOUD_USEOPACITY         5206
#define IDM_NAV_SWITCHCONTEXT           5300
#define IDM_INSPECTOR                   5400
#define IDM_INSPECTOR_SHOWINTERNAL      5401
#define IDM_INSPECTOR_SORTALPHABETIC    5402
#define IDM_INSPECTOR_EXPORTSUMMARY     5403
#define IDM_INSPECTOR_EXPORTMETADATA    5404
#define IDM_ORGANIZE                    6000
#define IDM_ORGANIZE_OPTIONS            6001
#define IDM_ORGANIZE_TOGGLEAUTODIRS     6002
#define IDM_ORGANIZE_FIRST              6003
#define IDM_VIEW                        7000
#define IDM_VIEW_FIRST                  7001
#define IDM_VIEW_LARGEICONS             7001
#define IDM_VIEW_SMALLICONS             7002
#define IDM_VIEW_LIST                   7003
#define IDM_VIEW_DETAILS                7004
#define IDM_VIEW_TILES                  7005
#define IDM_VIEW_STRIPS                 7006
#define IDM_VIEW_CONTENT                7007
#define IDM_VIEW_PREVIEW                7008
#define IDM_VIEW_CALENDAR               7009
#define IDM_VIEW_TIMELINE               7010
#define IDM_VIEW_GLOBE                  7011
#define IDM_VIEW_TAGCLOUD               7012
#define IDC_COMBO1                      8025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8011
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         8026
#define _APS_NEXT_SYMED_VALUE           8007
#endif
#endif
